# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 570)
        MainWindow.setMinimumSize(QSize(80, 80))
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.origin_img = QLabel(self.centralwidget)
        self.origin_img.setObjectName(u"origin_img")
        self.origin_img.setGeometry(QRect(10, 30, 330, 330))
        self.origin_img.setFrameShape(QFrame.Shape.Panel)
        self.result_img = QLabel(self.centralwidget)
        self.result_img.setObjectName(u"result_img")
        self.result_img.setGeometry(QRect(360, 30, 330, 330))
        self.result_img.setFrameShape(QFrame.Shape.Panel)
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(10, 415, 100, 50))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(False)
        self.save_button.setFont(font1)
        self.load_button = QPushButton(self.centralwidget)
        self.load_button.setObjectName(u"load_button")
        self.load_button.setEnabled(True)
        self.load_button.setGeometry(QRect(10, 360, 100, 50))
        self.load_button.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 0, 71, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.label.setFont(font2)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(500, 0, 81, 31))
        self.label_2.setFont(font2)
        self.color_space_Box = QComboBox(self.centralwidget)
        self.color_space_Box.addItem("")
        self.color_space_Box.addItem("")
        self.color_space_Box.addItem("")
        self.color_space_Box.setObjectName(u"color_space_Box")
        self.color_space_Box.setGeometry(QRect(110, 385, 100, 55))
        self.color_space_button = QPushButton(self.centralwidget)
        self.color_space_button.setObjectName(u"color_space_button")
        self.color_space_button.setGeometry(QRect(110, 440, 100, 80))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 360, 100, 31))
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.reset_button = QPushButton(self.centralwidget)
        self.reset_button.setObjectName(u"reset_button")
        self.reset_button.setGeometry(QRect(10, 470, 100, 50))
        self.reset_button.setFont(font1)
        self.geometric_Box = QComboBox(self.centralwidget)
        self.geometric_Box.addItem("")
        self.geometric_Box.addItem("")
        self.geometric_Box.addItem("")
        self.geometric_Box.addItem("")
        self.geometric_Box.setObjectName(u"geometric_Box")
        self.geometric_Box.setGeometry(QRect(210, 385, 100, 55))
        self.geometric_button = QPushButton(self.centralwidget)
        self.geometric_button.setObjectName(u"geometric_button")
        self.geometric_button.setGeometry(QRect(210, 440, 100, 80))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 360, 100, 31))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.blur_Box = QComboBox(self.centralwidget)
        self.blur_Box.addItem("")
        self.blur_Box.addItem("")
        self.blur_Box.addItem("")
        self.blur_Box.addItem("")
        self.blur_Box.setObjectName(u"blur_Box")
        self.blur_Box.setGeometry(QRect(410, 385, 100, 55))
        self.blur_button = QPushButton(self.centralwidget)
        self.blur_button.setObjectName(u"blur_button")
        self.blur_button.setGeometry(QRect(410, 440, 100, 80))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(410, 360, 100, 31))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(310, 360, 100, 31))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.noise_Box = QComboBox(self.centralwidget)
        self.noise_Box.addItem("")
        self.noise_Box.addItem("")
        self.noise_Box.setObjectName(u"noise_Box")
        self.noise_Box.setGeometry(QRect(310, 385, 100, 55))
        self.noise_button = QPushButton(self.centralwidget)
        self.noise_button.setObjectName(u"noise_button")
        self.noise_button.setGeometry(QRect(310, 440, 100, 80))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(510, 360, 100, 31))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edge_Box = QComboBox(self.centralwidget)
        self.edge_Box.addItem("")
        self.edge_Box.addItem("")
        self.edge_Box.addItem("")
        self.edge_Box.setObjectName(u"edge_Box")
        self.edge_Box.setGeometry(QRect(510, 385, 100, 55))
        self.edge_button = QPushButton(self.centralwidget)
        self.edge_button.setObjectName(u"edge_button")
        self.edge_button.setGeometry(QRect(510, 440, 100, 80))
        self.draw_button = QPushButton(self.centralwidget)
        self.draw_button.setObjectName(u"draw_button")
        self.draw_button.setGeometry(QRect(610, 385, 80, 135))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(600, 360, 100, 31))
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.origin_img.setText("")
        self.result_img.setText("")
        self.save_button.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u56fe\u50cf", None))
        self.load_button.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u56fe\u50cf", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u5904\u7406\u524d\u56fe\u50cf", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5904\u7406\u540e\u56fe\u50cf", None))
        self.color_space_Box.setItemText(0, QCoreApplication.translate("MainWindow", u"GRAY", None))
        self.color_space_Box.setItemText(1, QCoreApplication.translate("MainWindow", u"HSV", None))
        self.color_space_Box.setItemText(2, QCoreApplication.translate("MainWindow", u"YCrCb", None))

        self.color_space_button.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u6362\u8272\u5f69\u7a7a\u95f4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u7a7a\u95f4\u7c7b\u578b", None))
        self.reset_button.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u539f\u56fe", None))
        self.geometric_Box.setItemText(0, QCoreApplication.translate("MainWindow", u"\u6c34\u5e73\u7ffb\u8f6c", None))
        self.geometric_Box.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7ad6\u76f4\u7ffb\u8f6c", None))
        self.geometric_Box.setItemText(2, QCoreApplication.translate("MainWindow", u"\u987a\u65f6\u9488\u65cb\u8f6c", None))
        self.geometric_Box.setItemText(3, QCoreApplication.translate("MainWindow", u"\u9006\u65f6\u9488\u65cb\u8f6c", None))

        self.geometric_button.setText(QCoreApplication.translate("MainWindow", u"\u51e0\u4f55\u53d8\u6362", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u53d8\u6362\u65b9\u5f0f", None))
        self.blur_Box.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5747\u503c\u6ee4\u6ce2", None))
        self.blur_Box.setItemText(1, QCoreApplication.translate("MainWindow", u"\u4e2d\u503c\u6ee4\u6ce2", None))
        self.blur_Box.setItemText(2, QCoreApplication.translate("MainWindow", u"\u9ad8\u65af\u6ee4\u6ce2", None))
        self.blur_Box.setItemText(3, QCoreApplication.translate("MainWindow", u"\u4e8c\u7ef4\u5377\u79ef", None))

        self.blur_button.setText(QCoreApplication.translate("MainWindow", u"\u6ee4\u6ce2\u5904\u7406", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u6ee4\u6ce2\u65b9\u6cd5", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u566a\u58f0\u6837\u5f0f", None))
        self.noise_Box.setItemText(0, QCoreApplication.translate("MainWindow", u"\u9ad8\u65af\u566a\u58f0", None))
        self.noise_Box.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6912\u76d0\u566a\u58f0", None))

        self.noise_button.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u566a\u58f0", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u8fb9\u7f18\u68c0\u6d4b\u7b97\u5b50", None))
        self.edge_Box.setItemText(0, QCoreApplication.translate("MainWindow", u"Laplacian", None))
        self.edge_Box.setItemText(1, QCoreApplication.translate("MainWindow", u"Sobel", None))
        self.edge_Box.setItemText(2, QCoreApplication.translate("MainWindow", u"Canny", None))

        self.edge_button.setText(QCoreApplication.translate("MainWindow", u"\u8fb9\u7f18\u68c0\u6d4b", None))
        self.draw_button.setText(QCoreApplication.translate("MainWindow", u"\u5c55\u793a\u76f4\u65b9\u56fe", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u76f4\u65b9\u56fe\u7ed8\u5236", None))
    # retranslateUi

